### ISSUE TITLE
Release into F-Droid

### ISSUE THREAD

**Issue by DominicWrege** [Team-Ladefuchs/ladefuchs-android#34]
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by friesenkiwi** [comment]
F-Droid-MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13620

**Comment by friesenkiwi** [comment]
Noch isses nicht im store :)

**Comment by DominicWrege** [comment]
Dachte eher an marked as duplicate

**Comment by friesenkiwi** [comment]
OK, everything ready from the technical side, now waiting for F-Droid packagers :-)

**Comment by jugendhacker** [comment]
Hi, F-Droid Team Mitglied hier.

Seid ihr daran interessiert [reproduzierbare Builds](https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html) zu nutzen, damit die APK, die via F-Droid verteilt wird, auch mit eurem Key signiert ist oder ist es für euch okay das F-Droid die App APK mit dem eigenen Key signiert?

Vorteil von reproduzierbaren Builds wäre, dass Nutzer ohne großen Aufwand zwischen den F-Droid Builds und euren Builds wechseln könnten. Nachteil wäre, dass reproduzierbare Builds im Zweifel mehr Aufwand von eurer Seite erfordern.

**Comment by macschlingel** [comment]
> Hi, F-Droid Team Mitglied hier.
> 
> Seid ihr daran interessiert [reproduzierbare Builds](https://f-droid.org/2023/01/15/towards-a-reproducible-fdroid.html) zu nutzen, damit die APK, die via F-Droid verteilt wird, auch mit eurem Key signiert ist oder ist es für euch okay das F-Droid die App APK mit dem eigenen Key signiert?
> 
> Vorteil von reproduzierbaren Builds wäre, dass Nutzer ohne großen Aufwand zwischen den F-Droid Builds und euren Builds wechseln könnten. Nachteil wäre, dass reproduzierbare Builds im Zweifel mehr Aufwand von eurer Seite erfordern.

Aktuell gibt es keine Daten, die nahelegen, dass Nutzer:innen das beim Ladefuchs wollen.

**Comment by jugendhacker** [comment]
Okay, eventuell noch sinnvoll zu erwähnen wäre, dass wenn ein Weg ausgewählt wurde und die ersten User via F-Droid installiert haben  ein wechsel nur noch schlecht möglich sein wird.

**Comment by macschlingel** [comment]
Wir verstehen den Punkt, sehen weiterhin keinen Need für einen Installationsquellenwechsel bei unseren Nutzer:innen. Ea gibt keine in der App persistierten Daten, welch Mensch durch ein de-install/re-install verlieren würde.

**Comment by jugendhacker** [comment]
Okay, eine Frage hätte ich dann noch: weder in eurer App noch auf der Website finde ich Informationen zum Thema Datenschutz, Umgang mit Log Files, eventueller Verarbeitung der anfallenden Daten etc bei eurer API (die die App ja im Hintergrund nutzt). Übersehe ich das eventuell nur oder fehlt das wirklich?

**Comment by jugendhacker** [comment]
Wäre denke ich gut, das mal noch irgendwo zu verlinken (nicht zuletzt weil die DSGVO das meinem Laien Verständnis nach sogar fordert) aber zumindest bekommt ihr mit dieser Policy *kein* zusätzliches `Tracking` Anti Feature von F-Droid

**Comment by friesenkiwi** [comment]
@jugendhacker würde https://github.com/Team-Ladefuchs/ladefuchs-android/pull/75#issue-1891245580 den Anspruch erstmal befriedigen?

Sind sonst noch Dinge zu ändern, um in F-Droid aufgenommen werden zu können?

**Comment by DominicWrege** [comment]
@jugendhacker wie schaut es aus ?

**Comment by DominicWrege** [comment]
merged !
