### ISSUE TITLE
Ziel API Level anheben

### ISSUE THREAD

**Issue by gitlik** [Team-Ladefuchs/ladefuchs-android#70]
![image](https://github.com/Team-Ladefuchs/ladefuchs-android/assets/26041973/ec38c953-ef1a-454a-9131-029a3072dbe4)

**Comment by DominicWrege** [comment]
see: https://github.com/Team-Ladefuchs/ladefuchs-android/commit/205f05cc915e0d9dad85ec3825cc7647e67ea5d7
