### ISSUE TITLE
Wenn es keinen Preis gibt, auch wirklich keinen Preis eintragen statt 0,00 €

### ISSUE THREAD

**Issue by gitlik** [Team-Ladefuchs/ladefuchs-android#87]
So sollte es aussehen: ![image](https://github.com/Team-Ladefuchs/ladefuchs-android/assets/26041973/d7df5f74-9cdf-4272-97bc-71d94e0103c3)

**Comment by gitlik** [comment]
Diskussion: Alternativ einen Strich `—` eintragen, macht das deutlicher, dass es diese Option nicht gibt?

**Comment by Thorsten1** [comment]
- finde ich gut.

**Comment by amenk** [comment]
Ich würde das gerade mal umsetzen. Was haltet ihr von Option B? Oder ist die Assoziation "Einhörner = Gibt es nicht zu umstritten" ;-) ?

A) <img src="https://github.com/Team-Ladefuchs/ladefuchs-android/assets/1087128/42bd2b5a-0e60-4e17-8831-75f8fc88ea81" width="40%"> B) <img src="https://github.com/Team-Ladefuchs/ladefuchs-android/assets/1087128/827a8b9e-3b10-42f8-9d49-5c73c3d59f20" width="40%">

**Comment by gitlik** [comment]
Ich bin für

—,--

**Comment by gitlik** [comment]
🚫 → "verboten" (was es nicht ist)
🦄 → ist aus meiner Sicht irreführend, ohne irgendeine Legende.

**Comment by amenk** [comment]
okay, ich ändere es auf —
